PLAYER_MAX_HEALTH = 9
PLAYER_MAX_SILK = 12
PLAYER_BASE_ATTACK_DAMAGE = 21

SILK_COST_CLAWLINE = 1
SILK_COST_SKILL = 4
SILK_COST_HEAL = 9

BOSS_MAX_HEALTH = 800

MAX_EPISODE_STEPS = 2000

NUM_RAYS = 32
NUM_HIT_TYPES = 6
RAYCAST_DIM = NUM_RAYS + NUM_RAYS * NUM_HIT_TYPES

NUM_BOSS_ANIMATION_STATES = 103
NUM_PLAYER_ANIMATION_STATES = 83

STATE_DIM = 21 + (NUM_BOSS_ANIMATION_STATES + 1) + (NUM_PLAYER_ANIMATION_STATES + 1)
OBSERVATION_DIM = STATE_DIM + RAYCAST_DIM

ARENA_MIN_X = 32.68
ARENA_MAX_X = 78.26
ARENA_MIN_Y = 95.0
ARENA_MAX_Y = 125.0

HERO_VEL_X_RANGE = (-70.0, 70.0)
HERO_VEL_Y_RANGE = (-35.0, 22.0)
BOSS_VEL_X_RANGE = (-67.0, 67.0)
BOSS_VEL_Y_RANGE = (-65.0, 60.0)
