using System.Collections.Generic;

namespace SilksongAgent;

public static class BossAnimationMapper
{
    private static readonly Dictionary<string, BossAnimationState> AnimationMap = new()
    {
        { "Idle", BossAnimationState.Idle },
        { "Combo Slash", BossAnimationState.ComboSlash },
        { "Antic", BossAnimationState.Antic },
        { "Rising Slash", BossAnimationState.RisingSlash },
        { "Charge Antic", BossAnimationState.ChargeAntic },
        { "RapidSlash Charge", BossAnimationState.RapidSlashCharge },
        { "TurnToIdle", BossAnimationState.TurnToIdle },
        { "Counter Stance", BossAnimationState.CounterStance },
        { "Engarde", BossAnimationState.Engarde },
        { "Evade", BossAnimationState.Evade },
        { "Forward Hop", BossAnimationState.ForwardHop },
        { "NPC Idle Right", BossAnimationState.NPCIdleRight },
        { "NPC Idle Turn Left", BossAnimationState.NPCIdleTurnLeft },
        { "NPC Idle Left", BossAnimationState.NPCIdleLeft },
        { "NPC Idle Turn Right", BossAnimationState.NPCIdleTurnRight },
        { "Possession", BossAnimationState.Possession },
        { "Stun", BossAnimationState.Stun },
        { "Charge", BossAnimationState.Charge },
        { "Charge Recover", BossAnimationState.ChargeRecover },
        { "Downstab Antic", BossAnimationState.DownstabAntic },
        { "Downstab", BossAnimationState.Downstab },
        { "Downstab End", BossAnimationState.DownstabEnd },
        { "Counter Antic", BossAnimationState.CounterAntic },
        { "Counter End", BossAnimationState.CounterEnd },
        { "Counter Hit", BossAnimationState.CounterHit },
        { "RapidSlash End", BossAnimationState.RapidSlashEnd },
        { "RapidSlash Loop", BossAnimationState.RapidSlashLoop },
        { "RapidSlash Effect", BossAnimationState.RapidSlashEffect },
        { "Jump Antic", BossAnimationState.JumpAntic },
        { "Conduct", BossAnimationState.Conduct },
        { "CrossSlash Antic", BossAnimationState.CrossSlashAntic },
        { "Conduct End", BossAnimationState.ConductEnd },
        { "Stun Air", BossAnimationState.StunAir },
        { "Stun Recover", BossAnimationState.StunRecover },
        { "Jump AnticQ", BossAnimationState.JumpAnticQ },
        { "Jump Away", BossAnimationState.JumpAway },
        { "Eye Flash", BossAnimationState.EyeFlash },
        { "MultiHit Slash", BossAnimationState.MultiHitSlash },
        { "Pose Lean", BossAnimationState.PoseLean },
        { "Pose Upright", BossAnimationState.PoseUpright },
        { "Pose Swish", BossAnimationState.PoseSwish },
        { "Dash Burst", BossAnimationState.DashBurst },
        { "AirDash Burst", BossAnimationState.AirDashBurst },
        { "Stun Hit", BossAnimationState.StunHit },
        { "Trap Stun", BossAnimationState.TrapStun },
        { "Pose Hornet Defeated", BossAnimationState.PoseHornetDefeated },
        { "NPC Sit", BossAnimationState.NPCSit },
        { "Swish Block", BossAnimationState.SwishBlock },
        { "ConductToIdle", BossAnimationState.ConductToIdle },
        { "NPC Sit Antic", BossAnimationState.NPCSitAntic },
        { "NPC SitLook", BossAnimationState.NPCSitLook },
        { "SitToIdle", BossAnimationState.SitToIdle },
        { "Combo Slash Q", BossAnimationState.ComboSlashQ },
        { "Downstab Antic Q", BossAnimationState.DownstabAnticQ },
        { "Bomb Slash Antic", BossAnimationState.BombSlashAntic },
        { "Bomb Slash", BossAnimationState.BombSlash },
        { "Fall", BossAnimationState.Fall },
        { "Land", BossAnimationState.Land },
        { "Death 1", BossAnimationState.Death1 },
        { "Death 2", BossAnimationState.Death2 },
        { "Lie", BossAnimationState.Lie },
        { "LieToWake", BossAnimationState.LieToWake },
        { "Combo Slash Triple", BossAnimationState.ComboSlashTriple },
        { "P2 Shift Old", BossAnimationState.P2ShiftOld },
        { "ChargeMulti Antic", BossAnimationState.ChargeMultiAntic },
        { "ChargeMulti", BossAnimationState.ChargeMulti },
        { "ChargeMulti Recover", BossAnimationState.ChargeMultiRecover },
        { "Rising Slash Multi", BossAnimationState.RisingSlashMulti },
        { "Roar", BossAnimationState.Roar },
        { "Death Stagger", BossAnimationState.DeathStagger },
        { "Laugh", BossAnimationState.Laugh },
        { "Tele In", BossAnimationState.TeleIn },
        { "Death Air", BossAnimationState.DeathAir },
        { "Death Land Stun", BossAnimationState.DeathLandStun },
        { "Tele Out", BossAnimationState.TeleOut },
        { "Wall Bounce", BossAnimationState.WallBounce },
        { "Charge Crossup", BossAnimationState.ChargeCrossup },
        { "Quick Slash", BossAnimationState.QuickSlash },
        { "RapidSlashAir TeleIn", BossAnimationState.RapidSlashAirTeleIn },
        { "RapidSlashAir", BossAnimationState.RapidSlashAir },
        { "Sing", BossAnimationState.Sing },
        { "Sing End", BossAnimationState.SingEnd },
        { "RapidSlashAir End", BossAnimationState.RapidSlashAirEnd },
        { "Tele Out Fast", BossAnimationState.TeleOutFast },
        { "Counter Antic Fast", BossAnimationState.CounterAnticFast },
        { "MultiHit Slash Air", BossAnimationState.MultiHitSlashAir },
        { "Multihit AirEnd", BossAnimationState.MultihitAirEnd },
        { "P2 Shift", BossAnimationState.P2Shift },
        { "Mid Battle Roar", BossAnimationState.MidBattleRoar },
        { "Counter Flash", BossAnimationState.CounterFlash },
        { "RapidSlashAir End Q", BossAnimationState.RapidSlashAirEndQ },
        { "Swish Block Long", BossAnimationState.SwishBlockLong },
        { "Combo Strike 1", BossAnimationState.ComboStrike1 },
        { "Combo Strike 2", BossAnimationState.ComboStrike2 },
        { "Charge Strike", BossAnimationState.ChargeStrike },
        { "Downstab Strike", BossAnimationState.DownstabStrike },
        { "Downstab Followup", BossAnimationState.DownstabFollowup },
        { "Forward Hop Intro", BossAnimationState.ForwardHopIntro },
        { "Combo Slash LongAntic", BossAnimationState.ComboSlashLongAntic },
        { "Forward Hop Slow", BossAnimationState.ForwardHopSlow },
        { "Lava Damage", BossAnimationState.LavaDamage },
        { "Tele In Fast", BossAnimationState.TeleInFast },
    };

    public static BossAnimationState GetAnimationState(string clipName)
    {
        if (string.IsNullOrEmpty(clipName))
            return BossAnimationState.Unknown;

        return AnimationMap.TryGetValue(clipName, out var state) ? state : BossAnimationState.Unknown;
    }
}