using System.Collections.Generic;

namespace SilksongAgent;

public static class PlayerAnimationMapper
{
    private static readonly Dictionary<string, PlayerAnimationState> AnimationMap = new()
    {
        { "Idle", PlayerAnimationState.Idle },
        { "Airborne", PlayerAnimationState.Airborne },
        { "Land", PlayerAnimationState.Land },
        { "Idle To Run", PlayerAnimationState.IdleToRun },
        { "Run To Idle", PlayerAnimationState.RunToIdle },
        { "Turn", PlayerAnimationState.Turn },
        { "Wound Double Strike", PlayerAnimationState.WoundDoubleStrike },
        { "Stun", PlayerAnimationState.Stun },
        { "Recoil", PlayerAnimationState.Recoil },
        { "Dash", PlayerAnimationState.Dash },
        { "Sprint", PlayerAnimationState.Sprint },
        { "Dash To Idle", PlayerAnimationState.DashToIdle },
        { "SlashAlt", PlayerAnimationState.SlashAlt },
        { "Slash Land Run Alt", PlayerAnimationState.SlashLandRunAlt },
        { "Dash Attack Antic", PlayerAnimationState.DashAttackAntic },
        { "Slash Land", PlayerAnimationState.SlashLand },
        { "Dash To Run", PlayerAnimationState.DashToRun },
        { "UpSlash", PlayerAnimationState.UpSlash },
        { "Slash", PlayerAnimationState.Slash },
        { "DownSpike Antic", PlayerAnimationState.DownSpikeAntic },
        { "DownSpike", PlayerAnimationState.DownSpike },
        { "Downspike Recovery", PlayerAnimationState.DownspikeRecovery },
        { "DownSpikeBounce 2", PlayerAnimationState.DownSpikeBounce2 },
        { "DownSpikeBounce 1", PlayerAnimationState.DownSpikeBounce1 },
        { "Recoil Twirl", PlayerAnimationState.RecoilTwirl },
        { "Land To Run", PlayerAnimationState.LandToRun },
        { "Skid End 1", PlayerAnimationState.SkidEnd1 },
        { "Harpoon Antic", PlayerAnimationState.HarpoonAntic },
        { "Harpoon Throw", PlayerAnimationState.HarpoonThrow },
        { "Harpoon Dash", PlayerAnimationState.HarpoonDash },
        { "Harpoon Catch", PlayerAnimationState.HarpoonCatch },
        { "Silk Charge End", PlayerAnimationState.SilkChargeEnd },
        { "Air Dash", PlayerAnimationState.AirDash },
        { "Sprint Air", PlayerAnimationState.SprintAir },
        { "Sprint Air Loop", PlayerAnimationState.SprintAirLoop },
        { "NeedleThrow AnticG", PlayerAnimationState.NeedleThrowAnticG },
        { "NeedleThrow Throwing", PlayerAnimationState.NeedleThrowThrowing },
        { "NeedleThrow Catch", PlayerAnimationState.NeedleThrowCatch },
        { "Double Jump", PlayerAnimationState.DoubleJump },
        { "Walljump", PlayerAnimationState.Walljump },
        { "Wall Slide", PlayerAnimationState.WallSlide },
        { "Dash Attack", PlayerAnimationState.DashAttack },
        { "Dash Attack Recover", PlayerAnimationState.DashAttackRecover },
        { "Slash To Run", PlayerAnimationState.SlashToRun },
        { "Run", PlayerAnimationState.Run },
        { "Skid End 2", PlayerAnimationState.SkidEnd2 },
        { "Sprint Air Short", PlayerAnimationState.SprintAirShort },
        { "Mantle Cling", PlayerAnimationState.MantleCling },
        { "Mantle Vault", PlayerAnimationState.MantleVault },
        { "Slash Land Run", PlayerAnimationState.SlashLandRun },
        { "Wound", PlayerAnimationState.Wound },
        { "Hazard Respawn", PlayerAnimationState.HazardRespawn },
        { "Mantle Land", PlayerAnimationState.MantleLand },
        { "Mantle Land To Run", PlayerAnimationState.MantleLandToRun },
        { "Sprint Turn", PlayerAnimationState.SprintTurn },
        { "NeedleThrow AnticA", PlayerAnimationState.NeedleThrowAnticA },
        { "Umbrella Inflate Antic", PlayerAnimationState.UmbrellaInflateAntic },
        { "Umbrella Inflate", PlayerAnimationState.UmbrellaInflate },
        { "Umbrella Float", PlayerAnimationState.UmbrellaFloat },
        { "Downspike Recovery Land", PlayerAnimationState.DownspikeRecoveryLand },
        { "Dash Down", PlayerAnimationState.DashDown },
        { "Shuttlecock Antic", PlayerAnimationState.ShuttlecockAntic },
        { "Shuttlecock", PlayerAnimationState.Shuttlecock },
        { "Sprint Backflip", PlayerAnimationState.SprintBackflip },
        { "Umbrella Deflate", PlayerAnimationState.UmbrellaDeflate },
        { "Dash Down Land", PlayerAnimationState.DashDownLand },
        { "Umbrella Turn", PlayerAnimationState.UmbrellaTurn },
        { "Mantle Cancel To Jump", PlayerAnimationState.MantleCancelToJump },
        { "Idle Hurt", PlayerAnimationState.IdleHurt },
        { "LookDown", PlayerAnimationState.LookDown },
        { "LookDownEnd", PlayerAnimationState.LookDownEnd },
        { "LookUp", PlayerAnimationState.LookUp },
        { "LookUpEnd", PlayerAnimationState.LookUpEnd },
        { "BindCharge Ground", PlayerAnimationState.BindChargeGround },
        { "BindBurst Ground", PlayerAnimationState.BindBurstGround },
        { "BindCharge Air", PlayerAnimationState.BindChargeAir },
        { "BindBurst Air", PlayerAnimationState.BindBurstAir },
        { "Fall", PlayerAnimationState.Fall },
        { "Wall Cling", PlayerAnimationState.WallCling },
        { "Walljump Antic", PlayerAnimationState.WalljumpAntic },
        { "HardLand", PlayerAnimationState.HardLand },
        { "Walk", PlayerAnimationState.Walk },
    };

    public static PlayerAnimationState GetAnimationState(string clipName)
    {
        if (string.IsNullOrEmpty(clipName))
            return PlayerAnimationState.Unknown;

        return AnimationMap.TryGetValue(clipName, out var state) ? state : PlayerAnimationState.Unknown;
    }
}
